// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/gfm.css.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/static/[id].ts";
import * as $$0 from "./islands/BotTokenInput.tsx";
import * as $$1 from "./islands/RunButton.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/gfm.css.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/static/[id].ts": $3,
  },
  islands: {
    "./islands/BotTokenInput.tsx": $$0,
    "./islands/RunButton.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
